name:                login-with-twitter-middleware
version:             0.1.0.0
github:              "githubuser/login-with-twitter-middleware"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 kamoii"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/login-with-twitter-middleware#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- http-types
- http-client
- http-client-tls
- cookie
- text
- bytestring
- authenticate-oauth
- containers
- twitter-conduit
- twitter-types
- vault

library:
  source-dirs: src

executables:
  login-with-twitter-middleware-sample:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relude
    - scotty
    - lucid
    - cookie
    - time
    - base64-bytestring
    - login-with-twitter-middleware

# tests:
#   login-with-twitter-middleware-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - login-with-twitter-middleware
